// ALTE_DATEIEN/webui-vue-reference/src/views/History.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useHistoryBackend } from '../composables/useHistoryBackend'
import { useTelemetry } from '../composables/useTelemetry'

const { events, sessions, summary, loading, error, lastUpdated, refreshHistoryData } = useHistoryBackend()
const { telemetry } = useTelemetry()

const timeFilter = ref<'all' | '24h' | '7d' | '30d'>('7d')
const typeFilter = ref('all')
const stateFilter = ref('all')
const onlyMissionEnds = ref(false)

function cutoffMs() {
  const now = Date.now()
  if (timeFilter.value === '24h') return now - 24 * 60 * 60 * 1000
  if (timeFilter.value === '7d') return now - 7 * 24 * 60 * 60 * 1000
  if (timeFilter.value === '30d') return now - 30 * 24 * 60 * 60 * 1000
  return 0
}

const eventTypes = computed(() =>
  [...new Set(events.value.map(e => e.event_type).filter(Boolean))].sort()
)

const statePhases = computed(() =>
  [...new Set([
    ...events.value.map(e => e.state_phase),
    ...sessions.value.map(s => mapSessionState(s)),
  ].filter(Boolean))].sort()
)

function mapSessionState(session: { metadata?: Record<string, unknown> }) {
  const raw = session.metadata?.state_phase
  return typeof raw === 'string' && raw ? raw : 'mowing'
}

const filteredEvents = computed(() => {
  const cutoff = cutoffMs()
  return events.value.filter((event) => {
    if (cutoff > 0 && event.ts_ms < cutoff) return false
    if (typeFilter.value !== 'all' && event.event_type !== typeFilter.value) return false
    if (stateFilter.value !== 'all' && event.state_phase !== stateFilter.value) return false
    if (onlyMissionEnds.value) {
      return event.event_type === 'state_transition' && event.event_reason !== 'mission_active'
    }
    return true
  })
})

const filteredSessions = computed(() => {
  const cutoff = cutoffMs()
  return sessions.value.filter((session) => {
    if (cutoff > 0 && session.started_at_ms < cutoff) return false
    if (stateFilter.value !== 'all' && mapSessionState(session) !== stateFilter.value) return false
    if (onlyMissionEnds.value && !session.ended_at_ms) return false
    return true
  })
})

const recording = computed(() => telemetry.value.state_phase === 'mowing')
const exportUrl = computed(() => summary.value?.export_enabled ? '/api/history/export' : '')

function fmtDateTime(ms: number) {
  return new Date(ms).toLocaleString('de-DE', {
    day: '2-digit', month: '2-digit', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}

function fmtDuration(ms: number) {
  const h = Math.floor(ms / 3_600_000)
  const m = Math.floor((ms % 3_600_000) / 60_000)
  const s = Math.floor((ms % 60_000) / 1_000)
  if (h > 0) return `${h}h ${m.toString().padStart(2, '0')}m`
  if (m > 0) return `${m}m ${s.toString().padStart(2, '0')}s`
  return `${s}s`
}

function fmtDist(m: number) {
  return m >= 1000 ? `${(m / 1000).toFixed(2)} km` : `${Math.round(m)} m`
}

function fmtBattery(start: number, end: number) {
  const delta = end - start
  const sign = delta >= 0 ? '+' : ''
  return `${start.toFixed(1)} V → ${end.toFixed(1)} V (${sign}${delta.toFixed(1)} V)`
}

function lastUpdatedText() {
  if (!lastUpdated.value) return 'noch nicht geladen'
  return fmtDateTime(lastUpdated.value)
}
</script>

<template>
  <div class="history-wrap">
    <div class="history-header">
      <div>
        <h2 class="history-title">Verlauf</h2>
        <p class="history-sub">
          Backend-gestuetzte Ereignisse und Mäh-Sessions.
        </p>
      </div>
      <div class="history-actions">
        <span v-if="recording" class="history-badge">Session laeuft</span>
        <a v-if="exportUrl" class="history-btn secondary" :href="exportUrl">DB exportieren</a>
        <button class="history-btn" @click="refreshHistoryData">Aktualisieren</button>
      </div>
    </div>

    <div class="history-toolbar">
      <label>
        Zeitraum
        <select v-model="timeFilter">
          <option value="all">Gesamt</option>
          <option value="24h">24 Stunden</option>
          <option value="7d">7 Tage</option>
          <option value="30d">30 Tage</option>
        </select>
      </label>
      <label>
        Ereignistyp
        <select v-model="typeFilter">
          <option value="all">Alle</option>
          <option v-for="type in eventTypes" :key="type" :value="type">{{ type }}</option>
        </select>
      </label>
      <label>
        Zustand
        <select v-model="stateFilter">
          <option value="all">Alle</option>
          <option v-for="phase in statePhases" :key="phase" :value="phase">{{ phase }}</option>
        </select>
      </label>
      <label class="history-check">
        <input v-model="onlyMissionEnds" type="checkbox">
        Nur Missionsenden
      </label>
    </div>

    <div class="history-meta">
      <span>Letztes Update: {{ lastUpdatedText() }}</span>
      <span v-if="summary">Sessions gesamt: {{ summary.sessions_total }}</span>
      <span v-if="summary">Events gesamt: {{ summary.events_total }}</span>
      <span v-if="summary">Backend: {{ summary.backend_ready ? 'bereit' : 'nicht verfuegbar' }}</span>
    </div>

    <div v-if="loading" class="history-state">Lade Verlauf aus dem Backend…</div>
    <div v-else-if="error" class="history-state error">{{ error }}</div>

    <div v-else class="history-grid">
      <section class="history-section">
        <div class="history-section-head">
          <h3>Sessions</h3>
          <span>{{ filteredSessions.length }}</span>
        </div>
        <div v-if="filteredSessions.length === 0" class="history-empty">
          Keine Sessions fuer die gewaehlten Filter.
        </div>
        <article v-for="session in filteredSessions" :key="session.id" class="session-card">
          <div class="session-row">
            <strong>{{ fmtDateTime(session.started_at_ms) }}</strong>
            <span class="chip">{{ session.end_reason || 'laufend' }}</span>
          </div>
          <div class="session-grid">
            <span>Dauer: {{ fmtDuration(session.duration_ms) }}</span>
            <span>Strecke: {{ fmtDist(session.distance_m) }}</span>
            <span>Akku: {{ fmtBattery(session.battery_start_v, session.battery_end_v) }}</span>
            <span v-if="session.mean_gps_accuracy_m != null">
              GPS Ø: {{ session.mean_gps_accuracy_m.toFixed(2) }} m
            </span>
          </div>
        </article>
      </section>

      <section class="history-section">
        <div class="history-section-head">
          <h3>Ereignisse</h3>
          <span>{{ filteredEvents.length }}</span>
        </div>
        <div v-if="filteredEvents.length === 0" class="history-empty">
          Keine Ereignisse fuer die gewaehlten Filter.
        </div>
        <article v-for="event in filteredEvents" :key="`${event.ts_ms}-${event.event_type}-${event.message}`" class="event-card">
          <div class="event-row">
            <strong>{{ fmtDateTime(event.ts_ms) }}</strong>
            <div class="event-chips">
              <span class="chip">{{ event.event_type }}</span>
              <span class="chip muted">{{ event.state_phase || 'unknown' }}</span>
              <span v-if="event.error_code" class="chip error">{{ event.error_code }}</span>
            </div>
          </div>
          <p class="event-message">{{ event.message }}</p>
          <div class="event-meta">
            <span>Grund: {{ event.event_reason || 'none' }}</span>
            <span v-if="event.battery_v != null">Akku: {{ event.battery_v.toFixed(1) }} V</span>
            <span v-if="event.gps_sol != null">GPS: {{ event.gps_sol }}</span>
          </div>
        </article>
      </section>
    </div>
  </div>
</template>

<style scoped>
.history-wrap {
  padding: 16px;
  min-height: 100%;
  background: #0a0f1a !important;
  color: #e2e8f0;
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.history-header,
.history-toolbar,
.history-meta,
.history-section-head,
.session-row,
.event-row,
.event-meta {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
}

.history-header {
  justify-content: space-between;
}

.history-title {
  margin: 0;
  font-size: 16px;
}

.history-sub,
.history-meta,
.history-empty,
.event-meta {
  color: #8aa0ba;
  font-size: 12px;
}

.history-actions {
  display: flex;
  gap: 8px;
  align-items: center;
  flex-wrap: wrap;
}

.history-btn {
  border: 1px solid #2563eb;
  background: #2563eb !important;
  color: white !important;
  border-radius: 8px;
  padding: 8px 12px;
  cursor: pointer;
  text-decoration: none;
}

.history-btn.secondary {
  background: transparent !important;
  color: #93c5fd !important;
  border-color: #1e3a5f;
}

.history-badge,
.chip {
  display: inline-flex;
  align-items: center;
  padding: 4px 8px;
  border-radius: 999px;
  font-size: 11px;
  border: 1px solid #1e3a5f;
  background: #0f1829 !important;
}

.chip.muted {
  color: #8aa0ba !important;
}

.chip.error {
  border-color: #7f1d1d;
  color: #fecaca !important;
  background: #2a0d0d !important;
}

.history-toolbar label {
  display: flex;
  flex-direction: column;
  gap: 4px;
  font-size: 12px;
  color: #8aa0ba;
}

.history-toolbar select {
  min-width: 150px;
  background: #0f1829;
  color: #e2e8f0;
  border: 1px solid #1e3a5f;
  border-radius: 8px;
  padding: 8px 10px;
}

.history-check {
  flex-direction: row !important;
  align-items: center !important;
  margin-top: 18px;
}

.history-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 14px;
}

.history-section {
  background: #0f1829 !important;
  border: 1px solid #1e3a5f;
  border-radius: 14px;
  padding: 14px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.session-card,
.event-card {
  border: 1px solid #19314f;
  background: #09111d !important;
  border-radius: 12px;
  padding: 12px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.session-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 6px 12px;
  font-size: 12px;
  color: #d7e3f4;
}

.event-message {
  margin: 0;
  line-height: 1.45;
  font-size: 13px;
}

.event-chips {
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
  margin-left: auto;
}

.history-state {
  border-radius: 12px;
  padding: 14px;
  background: #0f1829 !important;
  border: 1px solid #1e3a5f;
}

.history-state.error {
  border-color: #7f1d1d;
  color: #fecaca;
  background: #2a0d0d !important;
}

@media (max-width: 720px) {
  .session-grid {
    grid-template-columns: 1fr;
  }
}
</style>

// webui-svelte/src/lib/pages/History.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import PageLayout from '../components/PageLayout.svelte'
  import { telemetry } from '../stores/telemetry'
  import {
    getHistoryEvents,
    getHistorySessions,
    getStatisticsSummary,
    type HistoryEventItem,
    type HistorySessionItem,
    type HistorySummaryResponse,
  } from '../api/rest'

  let sidebarCollapsed = false
  let loading = true
  let refreshing = false
  let error = ''

  let summary: HistorySummaryResponse | null = null
  let events: HistoryEventItem[] = []
  let sessions: HistorySessionItem[] = []

  function formatDate(tsMs?: number) {
    if (!tsMs) return '—'
    return new Date(tsMs).toLocaleString('de-DE', {
      dateStyle: 'short',
      timeStyle: 'medium',
    })
  }

  function formatDuration(durationMs?: number) {
    if (!durationMs) return '0 min'
    const totalSeconds = Math.max(0, Math.round(durationMs / 1000))
    const hours = Math.floor(totalSeconds / 3600)
    const minutes = Math.floor((totalSeconds % 3600) / 60)
    const seconds = totalSeconds % 60
    if (hours > 0) return `${hours} h ${minutes} min`
    if (minutes > 0) return `${minutes} min ${seconds}s`
    return `${seconds}s`
  }

  function formatMeters(distance?: number) {
    if (distance == null) return '—'
    return `${distance.toFixed(1)} m`
  }

  function formatVoltage(voltage?: number) {
    if (voltage == null) return '—'
    return `${voltage.toFixed(1)} V`
  }

  function toneForLevel(level: string) {
    if (level === 'error') return 'error'
    if (level === 'warn') return 'warn'
    return 'info'
  }

  function humanize(value: string) {
    if (!value) return '—'
    return value
      .replace(/^ERR_/, '')
      .replace(/_/g, ' ')
      .toLowerCase()
      .replace(/^\w/, (char) => char.toUpperCase())
  }

  function topCounts(source: Record<string, number> | undefined, limit = 8) {
    if (!source) return []
    return Object.entries(source)
      .sort((a, b) => b[1] - a[1])
      .slice(0, limit)
  }

  async function refreshHistory() {
    refreshing = true
    error = ''
    try {
      const [summaryResult, eventsResult, sessionsResult] = await Promise.all([
        getStatisticsSummary(),
        getHistoryEvents(40),
        getHistorySessions(20),
      ])

      summary = summaryResult
      events = eventsResult.items ?? []
      sessions = sessionsResult.items ?? []
    } catch (err) {
      error = err instanceof Error ? err.message : 'Verlauf konnte nicht geladen werden.'
    } finally {
      loading = false
      refreshing = false
    }
  }

  onMount(() => {
    void refreshHistory()
  })

  $: topReasons = topCounts(summary?.event_reason_counts)
  $: topTypes = topCounts(summary?.event_type_counts, 5)
  $: topLevels = topCounts(summary?.event_level_counts, 5)
  $: backendReady = summary?.backend_ready ?? false
</script>

<PageLayout
  {sidebarCollapsed}
  on:toggle={() => (sidebarCollapsed = !sidebarCollapsed)}
>
  <div class="history-page">
    <div class="hero">
      <div>
        <span class="eyebrow">Verlauf & Statistik</span>
        <h1>Feldereignisse, Sitzungen und Runtime-Trends</h1>
        <p>
          Diese Ansicht nutzt die persistierte History-DB und zeigt die wichtigsten
          Vorfälle direkt als Zähler, Sessions und letzte Ereignisse.
        </p>
      </div>

      <div class="hero-actions">
        <button type="button" class="refresh-btn" on:click={() => void refreshHistory()} disabled={refreshing}>
          {refreshing ? 'Aktualisiere…' : 'Aktualisieren'}
        </button>
        {#if summary?.export_enabled && summary?.database_exists}
          <a class="export-btn" href="/api/history/export">DB exportieren</a>
        {/if}
      </div>
    </div>

    {#if error}
      <div class="notice error">{error}</div>
    {/if}

    {#if loading}
      <div class="notice">Verlauf wird geladen…</div>
    {:else}
      <section class="stats-grid">
        <article class="stat-card">
          <span class="label">Backend</span>
          <strong>{backendReady ? 'bereit' : 'nicht bereit'}</strong>
          <span class="muted">
            {$telemetry.history_backend_ready ? 'Live-Telemetrie sieht Backend' : 'Telemetrie meldet kein Backend'}
          </span>
        </article>

        <article class="stat-card">
          <span class="label">Events gesamt</span>
          <strong>{summary?.events_total ?? 0}</strong>
          <span class="muted">Letztes Event {formatDate(summary?.last_event_ts_ms)}</span>
        </article>

        <article class="stat-card">
          <span class="label">Sessions</span>
          <strong>{summary?.sessions_completed ?? 0} / {summary?.sessions_total ?? 0}</strong>
          <span class="muted">Abgeschlossen / insgesamt</span>
        </article>

        <article class="stat-card">
          <span class="label">Mähzeit gesamt</span>
          <strong>{formatDuration(summary?.mowing_duration_ms_total)}</strong>
          <span class="muted">Strecke {formatMeters(summary?.mowing_distance_m_total)}</span>
        </article>
      </section>

      <section class="content-grid">
        <div class="panel wide">
          <div class="panel-header">
            <div>
              <span class="label">Top-Vorfallgründe</span>
              <h2>Häufigste Event-Gründe</h2>
            </div>
          </div>

          {#if topReasons.length === 0}
            <div class="empty">Noch keine gruppierten Ereignisgründe vorhanden.</div>
          {:else}
            <div class="count-grid">
              {#each topReasons as [reason, count]}
                <div class="count-card">
                  <strong>{count}</strong>
                  <span>{humanize(reason)}</span>
                </div>
              {/each}
            </div>
          {/if}
        </div>

        <div class="panel">
          <div class="panel-header">
            <div>
              <span class="label">Event-Arten</span>
              <h2>Typen</h2>
            </div>
          </div>
          <div class="mini-list">
            {#each topTypes as [type, count]}
              <div class="mini-row"><span>{humanize(type)}</span><strong>{count}</strong></div>
            {/each}
          </div>
        </div>

        <div class="panel">
          <div class="panel-header">
            <div>
              <span class="label">Severity</span>
              <h2>Level</h2>
            </div>
          </div>
          <div class="mini-list">
            {#each topLevels as [level, count]}
              <div class="mini-row"><span>{humanize(level)}</span><strong>{count}</strong></div>
            {/each}
          </div>
        </div>

        <div class="panel wide">
          <div class="panel-header">
            <div>
              <span class="label">Letzte Fahrten</span>
              <h2>Sitzungen</h2>
            </div>
          </div>

          {#if sessions.length === 0}
            <div class="empty">Noch keine Sessions gespeichert.</div>
          {:else}
            <div class="table-wrap">
              <table>
                <thead>
                  <tr>
                    <th>Start</th>
                    <th>Dauer</th>
                    <th>Strecke</th>
                    <th>Batterie</th>
                    <th>Ende</th>
                  </tr>
                </thead>
                <tbody>
                  {#each sessions as session}
                    <tr>
                      <td>{formatDate(session.started_at_ms)}</td>
                      <td>{formatDuration(session.duration_ms)}</td>
                      <td>{formatMeters(session.distance_m)}</td>
                      <td>{formatVoltage(session.battery_start_v)} → {formatVoltage(session.battery_end_v)}</td>
                      <td>{humanize(session.end_reason)}</td>
                    </tr>
                  {/each}
                </tbody>
              </table>
            </div>
          {/if}
        </div>

        <div class="panel wide">
          <div class="panel-header">
            <div>
              <span class="label">Letzte Ereignisse</span>
              <h2>Event-Stream</h2>
            </div>
          </div>

          {#if events.length === 0}
            <div class="empty">Noch keine Events gespeichert.</div>
          {:else}
            <div class="events">
              {#each events as event}
                <article class={`event-card ${toneForLevel(event.level)}`}>
                  <div class="event-top">
                    <span class="event-time">{formatDate(event.ts_ms)}</span>
                    <span class="event-level">{humanize(event.level)}</span>
                  </div>
                  <strong>{event.message || humanize(event.event_reason)}</strong>
                  <div class="event-meta">
                    <span>{humanize(event.event_type)}</span>
                    <span>{humanize(event.event_reason)}</span>
                    <span>{event.module || 'Robot'}</span>
                    {#if event.error_code}
                      <span>{event.error_code}</span>
                    {/if}
                  </div>
                </article>
              {/each}
            </div>
          {/if}
        </div>
      </section>
    {/if}
  </div>

  <svelte:fragment slot="sidebar">
    <div class="sidebar-header">
      <span class="eyebrow">History DB</span>
      <h2>Live-Kontext</h2>
      <p>Persistente Statistik plus aktueller Runtime-Zustand für schnelle Felddiagnose.</p>
    </div>

    <div class={`state-card ${backendReady ? 'success' : 'warning'}`}>
      <span class="label">Verfügbarkeit</span>
      <strong>{backendReady ? 'History aktiv' : 'History nicht bereit'}</strong>
      <span>{summary?.database_path || 'Pfad unbekannt'}</span>
    </div>

    <div class="state-card info">
      <span class="label">Live-Runtime</span>
      <strong>{$telemetry.runtime_health || 'ok'}</strong>
      <span>Op {$telemetry.op} · Grund {humanize($telemetry.event_reason)}</span>
      <span>Fehler {$telemetry.error_code || '—'}</span>
    </div>

    <div class="state-card">
      <span class="label">Retention</span>
      <strong>{summary?.retention.max_events ?? 0} Events</strong>
      <span>{summary?.retention.max_sessions ?? 0} Sessions</span>
    </div>

    <div class="state-card">
      <span class="label">Letzter Verlaufseintrag</span>
      <strong>{formatDate(summary?.last_event_ts_ms)}</strong>
      <span>Letzter Session-Start {formatDate(summary?.last_session_started_at_ms)}</span>
    </div>
  </svelte:fragment>
</PageLayout>

<style>
  .history-page {
    height: 100%;
    overflow-y: auto;
    padding: 1rem;
    display: grid;
    gap: 1rem;
    background:
      radial-gradient(circle at top left, rgba(14, 116, 144, 0.16), transparent 32%),
      linear-gradient(180deg, rgba(7, 13, 24, 0.98), rgba(10, 15, 26, 0.98));
  }

  .hero {
    display: flex;
    justify-content: space-between;
    gap: 1rem;
    align-items: end;
    padding: 1rem 1.1rem;
    border-radius: 1rem;
    background: rgba(15, 24, 41, 0.95);
    border: 1px solid #1e3a5f;
  }

  .eyebrow {
    display: inline-block;
    color: #67e8f9;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    font-size: 0.72rem;
    margin-bottom: 0.35rem;
  }

  h1,
  h2 {
    margin: 0;
  }

  .hero p,
  .sidebar-header p {
    margin: 0.45rem 0 0;
    color: #94a3b8;
    line-height: 1.45;
  }

  .hero-actions {
    display: flex;
    gap: 0.6rem;
    align-items: center;
    flex-wrap: wrap;
  }

  .refresh-btn,
  .export-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 0.7rem 0.95rem;
    border-radius: 0.65rem;
    border: 1px solid #1e3a5f;
    background: #10203a;
    color: #dbeafe;
    text-decoration: none;
    cursor: pointer;
    font-weight: 600;
  }

  .refresh-btn:disabled {
    opacity: 0.65;
    cursor: wait;
  }

  .export-btn {
    background: #0f3a2c;
    border-color: #14532d;
    color: #bbf7d0;
  }

  .notice {
    padding: 0.9rem 1rem;
    border-radius: 0.8rem;
    background: #0f1829;
    border: 1px solid #1e3a5f;
  }

  .notice.error {
    border-color: #7f1d1d;
    color: #fecaca;
  }

  .stats-grid {
    display: grid;
    grid-template-columns: repeat(4, minmax(0, 1fr));
    gap: 0.9rem;
  }

  .stat-card,
  .panel,
  .state-card {
    background: #0f1829;
    border: 1px solid #1e3a5f;
    border-radius: 0.9rem;
  }

  .stat-card {
    display: grid;
    gap: 0.25rem;
    padding: 1rem;
  }

  .stat-card strong {
    font-size: 1.5rem;
    color: #f8fafc;
  }

  .label {
    color: #7a8da8;
    font-size: 0.74rem;
    text-transform: uppercase;
    letter-spacing: 0.08em;
  }

  .muted {
    color: #94a3b8;
    font-size: 0.84rem;
  }

  .content-grid {
    display: grid;
    grid-template-columns: 1.5fr 1fr 1fr;
    gap: 1rem;
    align-items: start;
  }

  .panel {
    padding: 1rem;
    min-width: 0;
  }

  .panel.wide {
    grid-column: span 3;
  }

  .panel-header {
    display: flex;
    justify-content: space-between;
    align-items: end;
    gap: 0.75rem;
    margin-bottom: 0.85rem;
  }

  .count-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 0.75rem;
  }

  .count-card {
    display: grid;
    gap: 0.2rem;
    padding: 0.85rem;
    border-radius: 0.75rem;
    background: rgba(8, 47, 73, 0.24);
    border: 1px solid rgba(103, 232, 249, 0.18);
  }

  .count-card strong {
    font-size: 1.4rem;
    color: #cffafe;
  }

  .count-card span {
    color: #cbd5e1;
    line-height: 1.35;
  }

  .mini-list {
    display: grid;
    gap: 0.55rem;
  }

  .mini-row {
    display: flex;
    justify-content: space-between;
    gap: 1rem;
    padding: 0.75rem 0.85rem;
    border-radius: 0.7rem;
    background: rgba(15, 23, 42, 0.92);
  }

  .mini-row strong {
    color: #f8fafc;
  }

  .table-wrap {
    overflow-x: auto;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.92rem;
  }

  th,
  td {
    padding: 0.75rem 0.55rem;
    border-bottom: 1px solid rgba(30, 58, 95, 0.72);
    text-align: left;
  }

  th {
    color: #7a8da8;
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.08em;
  }

  .events {
    display: grid;
    gap: 0.75rem;
  }

  .event-card {
    display: grid;
    gap: 0.35rem;
    padding: 0.95rem 1rem;
    border-radius: 0.8rem;
    border: 1px solid #1e3a5f;
    background: rgba(15, 23, 42, 0.9);
  }

  .event-card.warn {
    border-color: #92400e;
  }

  .event-card.error {
    border-color: #7f1d1d;
  }

  .event-top,
  .event-meta {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem 0.85rem;
  }

  .event-time,
  .event-level,
  .event-meta {
    color: #94a3b8;
    font-size: 0.82rem;
  }

  .event-card strong {
    color: #f8fafc;
  }

  .empty {
    color: #94a3b8;
    padding: 0.5rem 0;
  }

  .sidebar-header {
    padding: 1rem;
    border-bottom: 1px solid #1e3a5f;
    display: grid;
    gap: 0.35rem;
  }

  .state-card {
    margin: 1rem;
    padding: 0.95rem 1rem;
    display: grid;
    gap: 0.25rem;
  }

  .state-card.success {
    border-color: #166534;
  }

  .state-card.warning {
    border-color: #92400e;
  }

  .state-card.info {
    border-color: #0f766e;
  }

  @media (max-width: 1100px) {
    .stats-grid {
      grid-template-columns: repeat(2, minmax(0, 1fr));
    }

    .content-grid {
      grid-template-columns: 1fr;
    }

    .panel.wide {
      grid-column: span 1;
    }
  }

  @media (max-width: 700px) {
    .hero {
      grid-template-columns: 1fr;
      display: grid;
    }

    .stats-grid {
      grid-template-columns: 1fr;
    }
  }
</style>
